/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NiHAThrift
{
  public enum TEAbstractionLevel
  {
    SEMANTIC_NODE = 0,
    CONCEPT_NODE = 1,
    INSTANCE_NODE = 2,
  }
}
