/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace NiHAThrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TEndPoint : TBase
  {

    public string Host { get; set; }

    public int Port { get; set; }

    public string NodeName { get; set; }

    public TEndPoint() {
    }

    public TEndPoint(string Host, int Port, string NodeName) : this() {
      this.Host = Host;
      this.Port = Port;
      this.NodeName = NodeName;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_Host = false;
        bool isset_Port = false;
        bool isset_NodeName = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Host = iprot.ReadString();
                isset_Host = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                Port = iprot.ReadI32();
                isset_Port = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                NodeName = iprot.ReadString();
                isset_NodeName = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_Host)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Host not set");
        if (!isset_Port)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Port not set");
        if (!isset_NodeName)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field NodeName not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TEndPoint");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Host == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Host not set");
        field.Name = "Host";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Host);
        oprot.WriteFieldEnd();
        field.Name = "Port";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Port);
        oprot.WriteFieldEnd();
        if (NodeName == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field NodeName not set");
        field.Name = "NodeName";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(NodeName);
        oprot.WriteFieldEnd();
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TEndPoint(");
      __sb.Append(", Host: ");
      __sb.Append(Host);
      __sb.Append(", Port: ");
      __sb.Append(Port);
      __sb.Append(", NodeName: ");
      __sb.Append(NodeName);
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
