/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NiHAThrift
{
  public enum TERepresentationType
  {
    SEMANTIC_NETWORK = 0,
    CONCEPTUAL_GRAPH = 1,
  }
}
