/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NiHAThrift
{
  public enum TESiginStatus
  {
    SIGNIN_SUCCESSFUL = 0,
    SIGNIN_NOT_SUCCESSFUL = 1,
  }
}
