/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace NiHAThrift
{
  public enum TESystemLevelType
  {
    INT16 = 0,
    INT32 = 1,
    INT64 = 2,
    DOUBLE = 3,
    BOOL = 4,
    STRING = 5,
    DATETIME = 6,
    IMAGE = 7,
    AUDIO = 8,
    VIDEO = 9,
    GRAPH = 10,
    DATAFILE = 11,
    DATASOURCE = 12,
  }
}
